pipeline {
	agent {
    
    	label 'docker'
    }
    
    stages {
        
        stage('Checkout') {
            steps {
                
                git poll: true,
                branch: 'master',
                credentialsId: '69826d2f-bc85-4608-bf45-a74ca34e9839',
               	url: 'git@github.com:greghodgkinson/ace-docker.git'                         
            }
        }
        
        stage('Build Base') {
            steps {
             	sh "cd 11.0.0.0/ace/ubuntu-1604/base; docker build -t ace:11.0.0.0 ."           
            }
        }
        
        stage('Build Bar + Base') {
            steps {
             	sh "cd 11.0.0.0/ace/ubuntu-1604/demo; docker build -t transformation_map:1.0 ."           
            }
        }
        
        stage('Run BAR') {
            steps {
             	sh "cd 11.0.0.0/ace/ubuntu-1604/demo;  docker run -d --name transformation_map -e LICENSE=accept -P transformation_map:1.0"           
            }
        }
             
    }
}